name: Main workflow

on: push

jobs:
  main:
    env:
      GITHUB_TOKEN: ${{ secrets.NEW_GITHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
    if: "github.ref == 'refs/heads/master'"
    name: "test commit deploy or ci skip"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}
      - name: Init git
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          echo "${SSH_PUB_KEY}" > ~/.ssh/id_rsa.pub
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
      - name: "echo message"
        run: |
          git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

          if [[ ! -e 'migrations' ]]; then
              mkdir 'migrations'
          elif [[ ! -d 'migrations' ]]; then
              echo "migrations already exists but is not a directory"
              exit 1
          fi

          cd migrations
          git clone git@github.com:edii/test_repo.git .
          ls -al

          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')
          #BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Ok RUN! [${BRANCH_NAME}]"

  ecr-push:
    if: github.ref == 'refs/heads/master' ||  github.head_ref == 'refs/heads/master'
    name: AWS ECR push
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}