name: Opened PR
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  opened-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get log commit
        id: log
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
      - name: show commit message
        run: echo ${steps.log.outputs.message}
      - name: Dump GitHub context
        if: "contains(steps.log.outputs.message, 'deploy')"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          BASE_BRANCH: ${{ github.base_ref }}
          HEAD_BRANCH: ${{ github.head_ref }}
        run: |
          echo "$GITHUB_CONTEXT"
          HEAD_BRANCH_REF=$(echo ${HEAD_BRANCH#refs/heads/} | sed 's/\//_/g')
          echo "BASE_BRANCH: [${BASE_BRANCH}] HEAD_BRANCH: [${HEAD_BRANCH_REF}]"