name: Opened PR
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  ecr-build-push:
    name: Git pull_request opened
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}

  repo-deploy:
    name: Git commited new manifest of flux
    runs-on: ubuntu-latest
    needs: ecr-build-push
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}
      - name: Get git commit shortsha
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})
      - name: Get log commit
        id: log
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
      - name: Add in Git infra new manifest
        if: "contains(steps.log.outputs.message, '/deploy')"
        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.PAT_FOR_PUSH}}
          COMMIT_MSG: "Generated new manifest"
          SHA: ${{ steps.vars.outputs.sha_short }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: ./.github/workflows/scripts/git_add_infra.sh